version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - ./TugasCRUD:/var/www/html
      - /var/www/html/vendor
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_mahasiswa
    ports:
      - "3306:3306"
    volumes:
      - ./db_mahasiswa.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10