name: CI/CD for PHP App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install PHPStan
        run: composer global require phpstan/phpstan

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run PHPUnit Tests
        run: |
          echo "No real tests yet, running dummy test"
          mkdir -p tests
          echo "<?php echo 'All tests passed'; ?>" > tests/DummyTest.php
          php tests/DummyTest.php

  sast:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run PHPStan (SAST)
        run: ~/.composer/vendor/bin/phpstan analyse --level=1 .