name: CI/CD for PHP App

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
  
      - name: Install Dependencies
        run: composer install
  
      - name: Grant Execute Permissions
        run: chmod +x vendor/bin/phpunit
  
      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit tests

  sast:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
  
      - name: Install Dependencies
        run: composer install
  
      - name: Grant Execute Permissions
        run: chmod +x vendor/bin/phpstan
  
      - name: Run PHPStan Analysis
        run: vendor/bin/phpstan analyse -c phpstan.neon

  deploy:
    needs: sast
    runs-on: ubuntu-latest
    steps:
      - name: Simulated Deploy
        run: echo "Deploy ke staging selesai!"
