name: CI/CD for PHP App

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  issues: write
  security-events: write
  actions: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Dependencies
        run: composer install --no-interaction --no-progress

      - name: Grant Execute Permissions for PHPUnit
        run: chmod +x vendor/bin/phpunit

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit tests

  sast:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install Dependencies
        run: composer install --no-interaction --no-progress

      - name: Grant Execute Permissions for PHPStan
        run: chmod +x vendor/bin/phpstan

      - name: Run PHPStan Analysis (SAST)
        run: vendor/bin/phpstan analyse -c phpstan.neon --level=4 --error-format=json > phpstan-report.json || true

      - name: Security Scan Dependencies with Composer Audit (SAST)
        run: composer audit --format=json > composer-audit-report.json || true

      - name: Upload SAST Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sast-reports
          path: |
            phpstan-report.json
            composer-audit-report.json
        if: success() || failure()

  dast:
    needs: sast
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start App with Docker Compose
        run: docker compose up -d

      - name: Wait for Database to be Ready
        run: |
          echo "Waiting for MySQL to be ready..."
          timeout 120 bash -c 'until docker compose exec -T db mysqladmin ping -h localhost --silent; do echo "Waiting for MySQL..."; sleep 2; done'
          echo "MySQL is ready!"

      - name: Debug Docker Compose Status
        run: |
          echo "=== Docker Compose Status ==="
          docker compose ps
          echo ""
          echo "=== Docker Images ==="
          docker images
          echo ""
          echo "=== Running Containers ==="
          docker ps -a
          echo ""
          echo "=== Check what's listening on port 8081 ==="
          ss -tlnp | grep 8081 || echo "Nothing listening on port 8081"
          netstat -tlnp | grep 8081 || echo "Nothing listening on port 8081 (netstat)"

      - name: Show Docker Logs
        run: |
          echo "=== Web Container Logs ==="
          docker compose logs web
          echo ""
          echo "=== DB Container Logs ==="
          docker compose logs db
        if: always()

      - name: Wait for App to Be Ready
        run: |
          timeout 120 bash -c 'until curl -sSf http://localhost:8081 >/dev/null; do echo "Waiting for app..."; sleep 2; done'

      - name: Verify App is Running
        run: |
          echo "Checking if app is responding..."
          echo "First, let's check what's actually running:"
          docker compose ps
          echo ""
          echo "Let's try different endpoints:"
          
          # Try localhost:8081 (correct port)
          echo "Trying localhost:8081..."
          curl -v http://localhost:8081 || echo "localhost:8081 failed"
          
          # Try 127.0.0.1:8081
          echo "Trying 127.0.0.1:8081..."
          curl -v http://127.0.0.1:8081 || echo "127.0.0.1:8081 failed"
          
          # Get container IP and try that
          CONTAINER_ID=$(docker compose ps -q web)
          if [ ! -z "$CONTAINER_ID" ]; then
            CONTAINER_IP=$(docker inspect $CONTAINER_ID | grep IPAddress | tail -1 | cut -d'"' -f4)
            if [ ! -z "$CONTAINER_IP" ]; then
              echo "Trying container IP: $CONTAINER_IP:80..."
              curl -v http://$CONTAINER_IP:80 || echo "Container IP failed"
            fi
          fi
          
          # Try to connect to container directly
          echo "Trying to exec into container..."
          docker compose exec -T web curl -v http://localhost || echo "Container internal curl failed"

      - name: Prepare ZAP Workspace
        run: |
          mkdir -p ${{ github.workspace }}/zap-reports
          chmod -R 777 ${{ github.workspace }}/zap-reports
    
      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        continue-on-error: true
        env:
          COMPOSER_NO_INTERACTION: 1
        with:
          target: 'http://web:80'
          fail_action: false
          cmd_options: '-a -d -m 2 -T 15 -z "-config spider.maxDuration=5"'
          artifact_name: 'zap-security-report'
          workdir: ${{ github.workspace }}/zap-reports


      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-reports
          path: ${{ github.workspace }}/zap-reports/report_*
        if: always()

      - name: Stop Docker Compose
        run: docker compose down
        if: always()

  deploy:
    needs: dast
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulated Deploy to Staging
        run: |
          echo "All security tests passed! Deploying to staging environment..."
          echo "Deployment timestamp: $(date)"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"

      - name: Notify deployment status
        run: |
          echo "✅ Deployment to staging completed successfully"
          echo "🔗 Staging URL: https://your-staging-url.com"
          echo "📊 Security scan results: Check the zap-security-reports artifact"
