name: CI/CD for PHP App

on:
  push:
    branches: [ "main" ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install Dependencies
        run: composer install

  test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install Dependencies
        run: composer install
      - name: Grant Execute Permissions to PHPUnit
        run: chmod +x vendor/bin/phpunit
      - name: Run Tests
        run: vendor/bin/phpunit

  sast:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PHPStan
        run: ~/.composer/vendor/bin/phpstan analyse --level=1 .

  deploy:
    needs: sast
    runs-on: ubuntu-latest
    steps:
      - name: Simulated Deploy
        run: echo "Deploy ke staging selesai!"
